var GAME_LEVELS = [
  ["                    xx                                                          ",
   "                    vv                                                x         ",
   "                                                                      x         ",
   "                                                                      x         ",
   "                                                                    x|xz        ",
   "                                                                  xxxxxx        ",
   "                                                                xxx!xxxxx       ",
   "                                     o                         xxx!!xxxxxx      ",
   "                                    xxx                       xxxxxxxxx!xxx     ",
   "                                                               xo !!!!!xxxx    ",
   "              o                                         x=         =!!!xxxxxx   ",
   "              x                                        xxo       x!!!!xxxxxx    ",
   "                                                        x      xxx!x!xxxxxx s   ",
   "        o    o o                   x  !!        xx!     x       xxvxxxxx        ",
   "        x   xxxxx         x   !!      !!         x!     xx         xxxx         ",
   "                    !!        !!      !!         x!     x                       ",
   "   @                !!      o !! o    !!     >   x!!!!!!x                       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],




  ["!!!!!!!!      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", //30
   "!!!!          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!                                                                                                               x",
   "!z            x  xx                                  x    x         x      x    x    x   o   x   o   x   o   x   x",
   "!xxxx                     x    x     x    x                             o                                         ",
   "!xxxx         x  xx                                  x    x         x      x    x    x   x   o   x   o   x   o    ", //25
   "!xxxx                                                                                                             ",
   "!xxxx                                                                                                             ",  
   "!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x   x   x   x|  x   x   x",
   "!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x       x       x       x",
   "xxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x       x       x       x",
   "xxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxx     xxx     xxx   ", //20
   "             ||                   xxxxxxxv                        xxxx                                            ",
   "                                   xxxxx    x  x                   xx      x                                      ",
   "    >                               xx                                                   x       x       x       x",
   "    xxxxxx                                              =                             x                           ",
   "      oo         xxx                        x  x                           x=            o   xx  o   xx  o   x   x", //15
   "    xxxxxx                           o                                                x       |                   ",
   "      oo         xxx                 x                  =                         xx     x       x       x      sx",
   "    xxxxxx                          xxxx    x  x                   xxx     x     xxxx                             ",
   "      oo                          xxxxxxxx                        xxxxx   ooo   xxxxxx                            ",
   "xxxxxxxxxxxxx!!xxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxx  x   x   x   x   x   x   x", //10
   "xxxxxxxxxx!!!!!xxxxxxxxx         xxxxxxxxxxxxxxxxxvvx           xxxxxxxxxxxxxxxxxxxxxx   x       x           x   x",
   "xxxxxxxxx!!!!!!xxxxxxxxx        sxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxxxxx   x       x           x   x",
   "xxxxxxxxxvxxxxxxxxxxxxxx         xxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxx   x   x   x   x   x   x   x",
   "                  x                                                                                   |           ",
   "     x   x   x   o  x                                                                        o  =o   o   o   o    ", //5
   "         o=                      xxxxxxx                                  xxxxxxxxxx     o   o   o   o   o   o  s ",
   "=      =        x             xxxxxxxxxx                @                 xxxxxxxxxx o o     o   o   o   o   o    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],




  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "z                                                                                                             ",
   "xx!!!!!!!!x                                                                                                   ",
   "xxxxxxxxxxx        o            o                                                                             ",
   "xv                xxx           x                                                                             ",
   "x                               =                                                                             ",
   "x                                                  x                                                          ",
   "x                                                  =                     o o              |                   ",
   "x                                                                        xxx                  o               ",
   "x                                                                                             x               ",
   "x                        o         xx       x                                                                 ",
   "x                                 !xx=      x                                                                 ",
   "x                               oxxxx      ox                       s                                         ",
   "x                   s           xxxxx      sx                       o                                         ",   
   "x x       @   o                xxxxxx       x>                                          =                o    ",
   "xxxxxxxxxxxxxxxxx   =   xxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],      
  ["                              ",
   "  xxx  xxxx xxxx xx x x xxxx  ",
   "  x x  x    x  x xx x x x     ",
   "  xxxx xxx  xxxx xxxx x xxx   ",
   "  x  x x    x x  x xx x x     ",
   "  xxxx xxxx x  x x xx x xxxx  ",
   "                              ",
   "@>                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                              ",
   " x   x  xxxx x  x x    xxxx   ",
   " x x x  x  x x  x x     x x   ",
   " xxxxx  x  x x  x x     x x   ",
   "  xxx   x  x x  x x     x x   ",
   "  x x   xxxx xxxx xxxx xxxx   ",
   "                              ",
   "                              ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              ",
   "    x  x  xxx x   x xxxx      ",
   "    x  x xx x x   x x         ",
   "    xxxx x  x  x x  xxx       ",
   "    x  x xxxx  x x  x         ",
   "    x  x x  x   x   xxxx      ",
   "                              ",
   "                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                              ",
   " x   x xxxx xx x   x   x   x  ",
   " x x x x  x xx x   x   x   x  ",
   " xxxxx x  x xxxx   x   x   x  ",
   "  xxx  x  x x xx              ",
   "  x x  xxxx x xx   x   x   x  ",
   "                              ",
   "                              ",
   "                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
